Update chat extension API for cache
SkygearIO/chat-SDK-iOS pull request #126
Opened 2017-11-17 02:23 UTC by Steven-Chan

connect #113

2017-11-20 03:43 UTC, rickmak requested changes
Just one comment, it looks good.

2017-11-20 03:43 UTC, rickmak commented on SKYKitChat/Classes/Core/SKYChatExtension.m
> +                          // TODO: call completion handler of the api
I think you missed to update the callback at 379e336.

2017-11-21 11:11 UTC, Steven-Chan commented
@rickmak updated

2017-11-22 08:18 UTC, Steven-Chan commented
@rickmak so sorry, lint failed, fixed

2017-11-22 08:40 UTC, merged