Implement fetch participant API with cache enabled
SkygearIO/chat-SDK-iOS pull request #206
Opened 2018-03-02 10:01 UTC by ben181231

Connect #196
Connect #197
Connect #198

2018-03-07 11:23 UTC, cheungpat requested changes

2018-03-07 11:23 UTC, cheungpat commented on SKYKitChat/Classes/Core/Cache/SKYChatCacheController.m
> +- (void)updateParticipants:(NSArray<SKYParticipant *> *)participants
`didFetchParticipant:(SKYParticipant *)` is better.

This is because the current design of controller API is supposed to be asynchronous. If following this logic `updateParticipants` is an action that should be asynchronous and have a completion handler.

The controller API also has other selectors for updating the cache store, but their name have a `did<Action><Object>` convention. The `updateParticipants` should follow that convention.

2018-03-07 11:23 UTC, cheungpat commented on SKYKitChat/Classes/UI/ConversationView/SKYChatConversationViewController.swift
> +        msg.creatorUserRecordID = self.senderId
👍

2018-03-07 11:23 UTC, cheungpat commented on SKYKitChat/Classes/UI/ConversationView/SKYChatConversationViewController.swift
> +                                                   didFetchedParticipants participants: [SKYParticipant])
urgh... please change it to `didFetchParticipants`

2018-03-09 06:28 UTC, ben181231 commented on SKYKitChat/Classes/Core/Cache/SKYChatCacheController.m
> +- (void)updateParticipants:(NSArray<SKYParticipant *> *)participants
If this API follows the APIs related to the ones for fetching message, it should be `- didFetchParticipants:(NSArray<SKYParticipant *> *)participants` __without__ completion handler, right?

The current APIs are:
```obj-c
- (void)fetchMessagesWithConversationID:(NSString *)conversationId
                                  limit:(NSInteger)limit
                        beforeMessageID:(NSString *)beforeMessageID
                                  order:(NSString *)order
                             completion:(SKYChatFetchMessagesListCompletion)completion;

- (void)fetchMessagesWithIDs:(NSArray<NSString *> *)messageIDs
                  completion:(SKYChatFetchMessagesListCompletion)completion;

- (void)didFetchMessages:(NSArray<SKYMessage *> *)messages
         deletedMessages:(NSArray<SKYMessage *> *)deletedMessages;
```

2018-03-12 04:07 UTC, merged