Fix voice message related issues
SkygearIO/chat-SDK-iOS pull request #213
Opened 2018-03-09 03:28 UTC by ben181231

Connect #207
Connect #210

2018-03-12 04:06 UTC, cheungpat requested changes

2018-03-12 04:06 UTC, cheungpat commented on SKYKitChat/Classes/UI/ConversationView/SKYChatConversationViewController.swift
> +            message: "Microphone permission is needed for sending voice messagae. " +
s/messagae/message/

2018-03-12 04:06 UTC, cheungpat commented on SKYKitChat/Classes/UI/ConversationView/SKYChatConversationViewController.swift
> +            if UIApplication.shared.canOpenURL(settingsUrl) {
Just open the URL without checking.

Alternatively, remove the `Settings` button if the app cannot open the URL.

2018-03-14 05:32 UTC, ben181231 commented
Updated.

2018-03-19 04:14 UTC, merged